name: Check Formatting

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    check-format:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Use specified Node version
              uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'
            - name: Instal Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version-file: '.bun-version'
            - name: Install dependencies
              run: bun install
            - name: Run ESLint
              run: bun lint
