name: Check Formatting

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Install dependencies
              run: yarn
            - name: Run ESLint
              run: yarn lint
