name: Deploy Functions

on:
  push:
    branches: ['main']
    paths:
      - 'functions/src'
      - 'functions/package.json'
      - 'functions/yarn.lock'
      - 'functions/tsconfig.json'
      - 'firebase.*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install modules
        run: |
          cd functions
          yarn
      - name: Build functions
        run: |
          cd functions
          yarn build
          yarn deploy
