# This is a basic workflow to help you get started with Actions

name: Deploy to Firebase Functions on merge

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
    push:
        branches: [main]
        paths:
            - 'functions/src'
            - 'functions/package.json'
            - 'functions/yarn.lock'
            - 'functions/tsconfig.json'
            - 'firebase.*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: |
                  cd functions
                  yarn
            # Deploying the functions to firebase
            - name: Deploy to Firebase
              uses: w9jds/firebase-action@master
              with:
                  args: deploy --only functions -p PROD
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
