name: Build Frontend

on:
    pull_request:
        branches: main
        paths:
            - 'src/**'
            - 'public/**'
            - 'firebase.json'
            - 'svelte.config.js'
            - 'vite.config.js'
            - 'postcss.config.cjs'
            - 'tailwind.config.cjs'
            - 'tsconfig.json'
            - 'yarn.lock'
    workflow_call:
        secrets:
            CLIENT_ID:
                required: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              run: yarn
            - name: Create .env file
              uses: SpicyPizza/create-envfile@v1.3
              with:
                  file_name: .env.production
                  fail_on_empty: true
                  envkey_PUBLIC_CLIENT_ID: ${{ secrets.CLIENT_ID }}
            - name: Build
              run: yarn build
            - name: Archive compiled files
              if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
              uses: actions/upload-artifact@v3
              with:
                  name: frontend-build
                  path: build
