name: Build Frontend

on:
    pull_request:
        branches: main
        paths:
            - 'src/**'
            - 'public/**'
            - 'firebase.json'
            - 'svelte.config.js'
            - 'vite.config.js'
            - 'postcss.config.cjs'
            - 'tailwind.config.cjs'
            - 'tsconfig.json'
            - 'bun.lock'
            - '.github/workflows/frontend-build.yml'
    workflow_call:
        secrets:
            CLIENT_ID:
                required: true

jobs:
    build-frontend:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Use specified Node version
              uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc'
            - name: Instal Bun
              uses: oven-sh/setup-bun@v2
              with:
                bun-version-file: '.bun-version'
            - name: Install dependencies
              run: bun install
            - name: Create .env file
              uses: SpicyPizza/create-envfile@v1.3
              with:
                  directory: frontend
                  file_name: .env.production
                  fail_on_empty: true
                  envkey_PUBLIC_CLIENT_ID: ${{ secrets.CLIENT_ID }}
            - name: Build
              run: bun build
            - name: Archive compiled files
              if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
              uses: actions/upload-artifact@v3
              with:
                  name: frontend-build
                  path: build
