name: Test Functions

on:
    pull_request:
        branches: main
        paths:
            - 'functions/**'
            - 'firebase.*'
            - '.github/workflows/functions-test.yml'
    workflow_call:
        secrets:
            SERVICE_ACCOUNT_KEY:
                required: true

jobs:
    test-functions:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Use specified Node version
              uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc'
            - name: Instal Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version-file: '.bun-version'
            - name: Install dependencies
              run: bun install --filter ./functions
            - name: Create service account key
              run: echo "$serviceAccountKey" >> ./functions/serviceAccountKey.json
              env:
                  serviceAccountKey: ${{ secrets.SERVICE_ACCOUNT_KEY }}
            - name: Run tests
              run: bun run --filter ./functions test
