name: Deploy Functions

on:
    push:
        branches: main
        paths:
            - 'functions/**'
            - 'firebase.*'
            - '.github/workflows/functions-deploy.yml'

jobs:
    deploy:
        name: Deploy functions
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Use Node v16
              uses: actions/setup-node@v3
              with:
                  node-version-file: 'functions/.nvmrc'
            - name: Install dependencies
              run: |
                yarn --cwd ./functions/
                rm ./functions/pnpm-lock.yaml
            - name: Get commit message
              run: |
                  MSG="${{ github.event.head_commit.message }}"
                  echo "commit_msg=${MSG%%$'\n'*}" >> "$GITHUB_ENV"
            - name: Deploy functions
              uses: w9jds/firebase-action@master
              with:
                  args: deploy --only functions --message \"${{ env.commit_msg }}\"
              env:
                  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
                  PROJECT_ID: ben-keys-spotify-tools
