name: Build Functions

on:
    pull_request:
        branches: main
        paths:
            - 'functions/**'
            - 'firebase.*'
            - 'bun.lock'
            - '.github/workflows/functions-build.yml'

jobs:
    build-functions:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Use specified Node version
              uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc'
            - name: Instal Bun
              uses: oven-sh/setup-bun@v2
              with:
                bun-version-file: '.bun-version'
            - name: Install dependencies
              run: pnpm  --C ./functions/ install
            - name: Build
              run: pnpm --C ./functions/ build
