name: Build Functions

on:
    pull_request:
        branches: main
        paths:
            - 'functions/**'
            - 'firebase.*'
    workflow_call:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version-file: 'functions/.nvmrc'
            - name: Install dependencies
              run: yarn --cwd ./functions/
            - name: Build
              run: yarn --cwd ./functions/ build
            - name: Archive compiled files
              if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
              uses: actions/upload-artifact@v3
              with:
                  name: functions-build
                  path: functions/lib
